<template>
  <v-main>
    <Hero/>
    <v-toolbar-title class="subHeader text-center">CREATE ACCOUNT</v-toolbar-title>
    <div class="block mainBlock">
      <v-container>
        <v-form ref="form" v-model="valid">
          <v-text-field ref="SellerName" v-model="seller.name" :rules="nameRules" label="Name / for clients to appear"
                        required></v-text-field>
          <v-text-field ref="SellerEmail" v-model="seller.email" :rules="emailRules" label="E-mail"
                        required></v-text-field>
          <v-text-field ref="SellerPhone" v-model="seller.phone" :rules="phoneRules"
                        label="Phone number / for clients to contact" required></v-text-field>
          <v-text-field ref="SellerUsername" v-model="seller.username" :rules="usernameRules" label="Username"
                        required></v-text-field>
          <v-text-field ref="SellerPassword" v-model="seller.password" :rules="passwordRules" label="Password"
                        :append-icon="value ? 'mdi-eye' : 'mdi-eye-off'"
                        @click:append="() => (value = !value)" :type="value ? 'password' : 'text'"
                        required></v-text-field>
          <v-checkbox v-model="checkbox" :rules="[v => !!v || 'You must agree to continue!']"
                      label="Agree with all policies" required></v-checkbox>
          <v-row>
            <v-dialog v-model="dialog" width="600px">
              <template v-slot:activator="{ on, /*attrs*/ }">
                <v-btn class="mr-4" v-on="on">Website Terms and Conditions</v-btn>
              </template>
              <v-card>
                <v-card-title>
                  <span class="headline">Website Terms and Conditions</span>
                </v-card-title>
                <v-card-text>
                  Website Terms and Conditions [Text Format]
                  Last updated [month day, year]

                  AGREEMENT TO TERMS
                  These Terms and Conditions constitute a legally binding agreement made between you, whether personally
                  or on behalf of an entity (“you”) and [business entity name] (“we,” “us” or “our”), concerning your
                  access to and use of the [website name.com] website as well as any other media form, media channel,
                  mobile website or mobile application related, linked, or otherwise connected thereto (collectively,
                  the “Site”).
                  You agree that by accessing the Site, you have read, understood, and agree to be bound by all of these
                  Terms and Conditions. If you do not agree with all of these Terms and Conditions, then you are
                  expressly prohibited from using the Site and you must discontinue use immediately.
                  Supplemental terms and conditions or documents that may be posted on the Site from time to time are
                  hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to
                  make changes or modifications to these Terms and Conditions at any time and for any reason.
                  We will alert you about any changes by updating the “Last updated” date of these Terms and Conditions,
                  and you waive any right to receive specific notice of each such change.
                  It is your responsibility to periodically review these Terms and Conditions to stay informed of
                  updates. You will be subject to, and will be deemed to have been made aware of and to have accepted,
                  the changes in any revised Terms and Conditions by your continued use of the Site after the date such
                  revised Terms and Conditions are posted.
                  The information provided on the Site is not intended for distribution to or use by any person or
                  entity in any jurisdiction or country where such distribution or use would be contrary to law or
                  regulation or which would subject us to any registration requirement within such jurisdiction or
                  country.
                  Accordingly, those persons who choose to access the Site from other locations do so on their own
                  initiative and are solely responsible for compliance with local laws, if and to the extent local laws
                  are applicable.
                  These terms and conditions were generated by Termly’s Terms and Conditions Generator.
                  Option 1: The Site is intended for users who are at least 18 years old. Persons under the age of 18
                  are not permitted to register for the Site.
                  Option 2: [The Site is intended for users who are at least 13 years of age.] All users who are minors
                  in the jurisdiction in which they reside (generally under the age of 18) must have the permission of,
                  and be directly supervised by, their parent or guardian to use the Site. If you are a minor, you must
                  have your parent or guardian read and agree to these Terms and Conditions prior to you using the Site.

                  INTELLECTUAL PROPERTY RIGHTS
                  Unless otherwise indicated, the Site is our proprietary property and all source code, databases,
                  functionality, software, website designs, audio, video, text, photographs, and graphics on the Site
                  (collectively, the “Content”) and the trademarks, service marks, and logos contained therein (the
                  “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark
                  laws and various other intellectual property rights and unfair competition laws of the United States,
                  foreign jurisdictions, and international conventions.
                  The Content and the Marks are provided on the Site “AS IS” for your information and personal use only.
                  Except as expressly provided in these Terms and Conditions, no part of the Site and no Content or
                  Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed,
                  encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any
                  commercial purpose whatsoever, without our express prior written permission.
                  Provided that you are eligible to use the Site, you are granted a limited license to access and use
                  the Site and to download or print a copy of any portion of the Content to which you have properly
                  gained access solely for your personal, non-commercial use. We reserve all rights not expressly
                  granted to you in and to the Site, the Content and the Marks.

                  USER REPRESENTATIONS
                  By using the Site, you represent and warrant that:
                  [(1) all registration information you submit will be true, accurate, current, and complete; (2) you
                  will maintain the accuracy of such information and promptly update such registration information as
                  necessary;]
                  (3) you have the legal capacity and you agree to comply with these Terms and Conditions;
                  [(4) you are not under the age of 13;]
                  (5) not a minor in the jurisdiction in which you reside [, or if a minor, you have received parental
                  permission to use the Site];
                  (6) you will not access the Site through automated or non-human means, whether through a bot, script,
                  or otherwise;
                  (7) you will not use the Site for any illegal or unauthorized purpose;
                  (8) your use of the Site will not violate any applicable law or regulation.
                  If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the
                  right to suspend or terminate your account and refuse any and all current or future use of the Site
                  (or any portion thereof).

                  USER REGISTRATION
                  You may be required to register with the Site. You agree to keep your password confidential and will
                  be responsible for all use of your account and password. We reserve the right to remove, reclaim, or
                  change a username you select if we determine, in our sole discretion, that such username is
                  inappropriate, obscene, or otherwise objectionable.

                  CONTACT US
                  In order to resolve a complaint regarding the Site or to receive further information regarding use of
                  the Site, please contact us at:
                  [Corporate Name]
                  [Corporate Address]
                  [Corporate Phone Number]
                  [Corporate Fax Number]
                  [Email Address]
                </v-card-text>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn color="blue darken-1" text @click="checkbox = false">Disagree</v-btn>
                  <v-btn color="blue darken-1" text @click="checkbox = true">Agree</v-btn>
                  <v-btn color="blue darken-1" text @click="dialog = false">Close</v-btn>
                </v-card-actions>
              </v-card>
            </v-dialog>
          </v-row>
          <v-row>
            <v-spacer></v-spacer>
            <v-btn :disabled="!valid" class="mr-4" @click="addSeller()">Submit
            </v-btn>
            <v-btn color="error" class="mr-4" @click="reset()">Reset</v-btn>
          </v-row>
        </v-form>
      </v-container>
    </div>
  </v-main>
</template>

<script>
import Hero from "@/components/Hero";
import router from "@/router";


let addSellerFunc = function () {
  let url = "http://localhost:8090/newSeller";
  this.$http.post(url, this.seller)
      .then(response => {alert(response.data.message)
        router.push("/login");})
      .catch(result => alert(result.response.data.message))
}
export default {
  name: 'CreateAccount',
  components: {
    Hero
  },

  data: () => ({
    dialog: false,
    valid: true,
    value: true,
    name: '',
    nameRules: [
      v => !!v || 'Name is required',
      v => (v && v.length <= 40) || 'Name must be less than 40 characters',
    ],
    email: '',
    emailRules: [
      v => !!v || 'E-mail is required',
      v => /.+@.+\..+/.test(v) || 'E-mail must be valid',
    ],
    phone: '',
    phoneRules: [
      v => !!v || 'Phone is required',
      v => (v && v.length > 6 && v.length < 20 && /^\+?\d*$/.test(v)) || 'Phone must be valid',
    ],
    username: '',
    usernameRules: [
      v => !!v || 'Username is required, minimum of 6 characters',
      v => (v && v.length > 5 && v.length < 20 && /./.test(v)) || 'Username should be at least 6 characters long',
    ],
    password: '',
    passwordRules: [
      v => !!v || 'Unique password is required',
      v => (v && v.length > 7 && v.length < 15 && /.*\d.*\d.*/.test(v)) || 'Min. 8 characters with at least 2 numbers',
    ],

    seller: {},
    checkbox: false,
    /*
    computed: {
      form() {
        return {
          sellerName: this.seller.Name,
          sellerEmail: this.seller.Email,
          sellerUsername: this.seller.Username,
          sellerPassword: this.seller.Passwoed,
          sellerPhone: this.seller.Phone,
        }
      },
    }*/
  }),

  methods: {
    validate() {
      this.$refs.form.validate()
    },
    addSeller: addSellerFunc,
    reset() {
      this.$refs.form.reset()
    },
  },
}
</script>


<style>

</style>
